version: '3.7'
services:
  consul1:
    image: consul:1.15
    container_name: consul_server1
    restart: always
    command: agent -server -client=0.0.0.0 -bootstrap-expect=3 -node=consul_server1
    volumes:
      - "../volumes/consul_volume/consul1/data:/consul/data"
      - "../volumes/consul_volume/consul1/config:/consul/config"
  consul2:
    image: consul:1.15
    container_name: consul_server2
    restart: always
    command: agent -server -client=0.0.0.0 -retry-join=consul_server1 -node=consul_server2
    volumes:
      - "../volumes/consul_volume/consul2/data:/consul/data"
      - "../volumes/consul_volume/consul2/config:/consul/config"
  consul3:
    image: consul:1.15
    container_name: consul_server3
    restart: always
    command: agent -server -client=0.0.0.0 -retry-join=consul_server1 -node=consul_server3
    volumes:
      - "../volumes/consul_volume/consul3/data:/consul/data"
      - "../volumes/consul_volume/consul3/config:/consul/config"
  consul4:
    image: consul:1.15
    container_name: consul_server4
    restart: always
    ports:
      - "8500:8500"
    command: agent -client=0.0.0.0 -retry-join=consul_server1 -ui -node=consul_server4
    volumes:
      - "../volumes/consul_volume/consul4/data:/consul/data"
      - "../volumes/consul_volume/consul4/config:/consul/config"