version: '3.7'
services:
  db:
    image: mysql:8
    restart: always
    container_name: "docker_mysql_8"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: ocean_mall
    volumes:
      - "../volumes/db_volume:/var/lib/mysql"
    expose:
      - "3307"
    ports:
      - "3307:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

