nacos:
  host: "192.168.1.16"
  port: 8848
  namespace: "ef612d04-5674-4f0d-911f-c91e534d3b47"
  dataId: "account_dev.json"
  group: "DEFAULT_GROUP"
#jwt:
#  sign_key: "Elian"
#
#consul:
#  host: "192.168.1.6"
#  port: "8500"
#
#redis:
#  host: "localhost"
#  port: "6380"
#
#mysql:
#  host: "localhost"
#  port: "3307"
#  userName: "root"
#  Password: "123456"
#  dbName: "ocean_mall_account"
#
#account_web:
#  srvName: "account_web"
#  host: "192.168.1.6"
#  port: "8085"
#  tags:
#    - ocean_mall
#    - account_web
#
#account_srv:
#  srvName: "account_srv"
#  host: "192.168.1.6"
#  port: "9095"
#  tags:
#    - ocean_mall
#    - account_srv
