jwt:
  sign_key: "Elian"

redis:
  host: "localhost"
  port: "6380"

mysql:
  host: "localhost"
  port: "3307"
  userName: "root"
  Password: "123456"
  dbName: "ocean_mall_account"

consul:
  host: "localhost"
  port: "8500"

account_srv:
  srvName: "account_srv"
  host: "localhost"
  port: "9095"
  tags:
    - ocean_mall
    - account_web